# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEoOs9WzXWxHbUqsZhYVWpuaejKd5SxI

# Partie 1 - Exploration et prétraitement des données

###Analyse exploratoire

*   Charger les données avec Pandas.
"""

import pandas as pd

df = pd.read_csv('tweets_suspect (2).csv')
df.head()

"""*   Identifier les variables disponibles."""

df.info()

"""
*   Vérifier les valeurs manquantes.

"""

df.isnull().sum()

"""
*   Étudier la distribution des classes.

"""

df['label'].value_counts()

"""*   Produire des visualisations pertinentes.


"""

import matplotlib.pyplot as plt
import seaborn as sns
# Visualisation de la distribution des classes
plt.figure(figsize=(8, 6))
sns.countplot(x='label', data=df, palette='viridis')
plt.title('Distribution des classes (label)')
plt.xlabel('Label')
plt.ylabel('Nombre de messages')
plt.xticks([0, 1], ['Négatif', 'Positif'])
plt.show()

"""###Prétraitement du texte

Mettre en œuvre plusieurs opérations de nettoyage :

*   Conversion en minuscules


"""

df['message'] = df['message'].str.lower()
display(df.head())

"""*   Suppression des caractères spéciaux.


"""

import re
df['message'] = df['message'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s.,!?]', '', x))
display(df.head())

"""*   Suppression des URLs"""

df['message'] = df['message'].apply(lambda x: re.sub(r'http\S+|www\S+', '', x))
display(df.head())

"""*   Suppression des stop words


"""

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('french'))

def remove_stopwords(text):
    return ' '.join([word for word in str(text).split() if word not in stop_words])

df['message'] = df['message'].apply(remove_stopwords)
display(df.head())

"""*   Lemmatisation ou stemming (optionnel).

    Pour notre cas nous avons choisi la Lemmatisation
"""

import nltk
nltk.download('punkt')
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    return ' '.join([lemmatizer.lemmatize(word) for word in str(text).split()])

df['message_lemmatized'] = df['message'].apply(lemmatize_text)
display(df[['message', 'message_lemmatized']].head())

"""Documenter les choix effectués.

Documentation des choix de prétraitement du texte
Voici un résumé des étapes de prétraitement appliquées au texte des messages:

1.   Conversion en minuscules: Tous les messages ont été convertis en minuscules pour assurer l'uniformité et réduire la complexité du vocabulaire.
2.   Suppression des caractères spéciaux et de la ponctuation non essentielle: Les caractères qui ne sont pas des lettres, des chiffres, des espaces ou de la ponctuation basique (.,!?) ont été retirés.
3.   Suppression des URLs: Les URLs (http:// ou www.) ont été supprimées des messages, car elles ne contribuent généralement pas à l'analyse du sentiment.
4.   Suppression des mots vides (Stopwords): Les mots courants en français (comme 'le', 'la', 'les', 'un', 'une', etc.) qui n'apportent pas de sens significatif au contexte du sentiment ont été retirés en utilisant la liste de stopwords de NLTK.

5.   Lemmatisation: Les mots ont été ramenés à leur forme canonique (lemme) pour réduire la variabilité lexicale et améliorer la précision de l'analyse, en utilisant le WordNetLemmatizer de NLTK.

#Partie 2 - Gestion des données avec DVC

###L'utilisation de GiT et DVC est obligatoire.
Vous devez :

Versionner le dataset

*   Initialiser DVC dans le projet.
"""

!pip install dvc

!dvc init -f --no-scm

"""*   Ajouter le dataset à DVC."""

!dvc add 'tweets_suspect (2).csv'

"""La commande !dvc add crée un fichier .dvc (ici, tweets_suspect (2).csv.dvc) qui stocke les métadonnées du fichier, comme son hachage et sa taille, sans stocker le fichier lui-même. C'est ce fichier .dvc qui est versionné, et non le fichier de données volumineux."""

!ls -la

"""Maintenant, nous pouvons vérifier le statut de DVC pour confirmer que le fichier a bien été ajouté.


"""

!dvc status

"""*   Configurer un stockage distant (local, Google Drive, S3, etc.).

Configurer le stockage distant DVC

Pour que DVC puisse stocker les données, nous devons configurer un dépôt distant. Il peut s'agir d'un stockage cloud comme Google Cloud Storage (GCS), Amazon S3, Azure Blob Storage, ou même un dossier local ou distant. Pour cet exemple, nous allons simuler un stockage local pour DVC.
"""

!mkdir /content/dvc_remote

!dvc remote add -d local /content/dvc_remote

"""Pousser les données vers le stockage distant

Une fois le stockage distant configuré, nous pouvons pousser les données suivies par DVC vers ce stockage. Cela transfère le contenu réel du fichier de données vers le cache DVC distant, et non le fichier .dvc lui-même.
"""

!dvc push

"""Vérifier les fichiers dans le stockage distant

Nous pouvons vérifier le contenu du dossier dvc_remote pour s'assurer que les données ont bien été poussées.
"""

!ls -la /content/dvc_remote

"""###Construire un pipeline DVC

Créer un pipeline comprenant au minimum :

1. Prétraitement des données

Nous allons créer un script preprocess.py qui effectuera les opérations de nettoyage et de lemmatisation. Le DataFrame prétraité sera sauvegardé dans un nouveau fichier CSV.
"""

# Sauvegarder le DataFrame prétraité (message_lemmatized et label) pour le pipeline DVC
df_pipeline = df[['message_lemmatized', 'label']]
df_pipeline.to_csv('tweets_suspect_preprocessed.csv', index=False)
print('Fichier tweets_suspect_preprocessed.csv créé.')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile preprocess.py
# import pandas as pd
# import re
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# 
# # Télécharger les ressources NLTK
# nltk.download('stopwords', quiet=True)
# nltk.download('punkt', quiet=True)
# nltk.download('wordnet', quiet=True)
# 
# stop_words = set(stopwords.words('french'))
# lemmatizer = WordNetLemmatizer()
# 
# def remove_stopwords(text):
#     return ' '.join([word for word in str(text).split() if word not in stop_words])
# 
# def lemmatize_text(text):
#     return ' '.join([lemmatizer.lemmatize(word) for word in str(text).split()])
# 
# def preprocess_data(input_path, output_path):
#     df = pd.read_csv(input_path)
# 
#     # Conversion en minuscules
#     df['message'] = df['message'].str.lower()
# 
#     # Suppression des caractères spéciaux et des URLs
#     df['message'] = df['message'].apply(lambda x: re.sub(r'http\S+|www\S+|[^a-zA-Z0-9\s.,!?]', '', x))
# 
#     # Suppression des stop words
#     df['message'] = df['message'].apply(remove_stopwords)
# 
#     # Lemmatisation
#     df['message_lemmatized'] = df['message'].apply(lemmatize_text)
# 
#     df[['message_lemmatized', 'label']].to_csv(output_path, index=False)
#     print(f'Données prétraitées sauvegardées dans {output_path}')
# 
# if __name__ == '__main__':
#     preprocess_data('tweets_suspect (2).csv', 'tweets_suspect_preprocessed.csv')

!dvc stage add -n preprocess --force \
        -d tweets_suspect\ \(2\).csv \
        -d preprocess.py \
        -o tweets_suspect_preprocessed.csv \
        python preprocess.py

"""2. Entraînement du modèle

Nous allons créer un script train.py pour entraîner un modèle de classification sur les données prétraitées et sauvegarder le modèle entraîné.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train.py
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.linear_model import LogisticRegression
# import joblib
# 
# def train_model(input_path, model_output_path):
#     df_preprocessed = pd.read_csv(input_path)
# 
#     # Gérer les valeurs manquantes si nécessaire (après lemmatisation, il peut y en avoir)
#     df_preprocessed['message_lemmatized'] = df_preprocessed['message_lemmatized'].fillna('')
# 
#     X = df_preprocessed['message_lemmatized']
#     y = df_preprocessed['label']
# 
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
# 
#     # Vectorisation TF-IDF
#     vectorizer = TfidfVectorizer(max_features=5000)
#     X_train_vectorized = vectorizer.fit_transform(X_train)
# 
#     # Entraînement du modèle (exemple: Régression Logistique)
#     model = LogisticRegression(max_iter=1000)
#     model.fit(X_train_vectorized, y_train)
# 
#     # Sauvegarder le modèle entraîné et le vectoriseur
#     joblib.dump(model, model_output_path)
#     joblib.dump(vectorizer, 'tfidf_vectorizer.pkl') # Sauvegarder le vectorizer aussi
# 
#     print(f'Modèle entraîné et sauvegardé dans {model_output_path}')
# 
# if __name__ == '__main__':
#     train_model('tweets_suspect_preprocessed.csv', 'model.pkl')

!dvc stage add -n train --force \
        -d tweets_suspect_preprocessed.csv \
        -d train.py \
        -o model.pkl \
        -o tfidf_vectorizer.pkl \
        python train.py

"""3. Évaluation du modèle

Nous allons créer un script evaluate.py pour évaluer la performance du modèle entraîné et sauvegarder les métriques dans un fichier JSON.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile evaluate.py
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score, classification_report
# import joblib
# import json
# 
# def evaluate_model(data_path, model_path, vectorizer_path, metrics_output_path):
#     df_preprocessed = pd.read_csv(data_path)
# 
#     # Gérer les valeurs manquantes si nécessaire
#     df_preprocessed['message_lemmatized'] = df_preprocessed['message_lemmatized'].fillna('')
# 
#     X = df_preprocessed['message_lemmatized']
#     y = df_preprocessed['label']
# 
#     # Re-diviser les données pour obtenir le même ensemble de test que l'entraînement
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
# 
#     # Charger le modèle et le vectoriseur
#     model = joblib.load(model_path)
#     vectorizer = joblib.load(vectorizer_path)
# 
#     # Transformer les données de test
#     X_test_vectorized = vectorizer.transform(X_test)
# 
#     # Prédictions
#     y_pred = model.predict(X_test_vectorized)
# 
#     # Calcul des métriques
#     accuracy = accuracy_score(y_test, y_pred)
#     report = classification_report(y_test, y_pred, output_dict=True)
# 
#     metrics = {
#         'accuracy': accuracy,
#         'classification_report': report
#     }
# 
#     with open(metrics_output_path, 'w') as f:
#         json.dump(metrics, f, indent=4)
# 
#     print(f'Métriques sauvegardées dans {metrics_output_path}')
# 
# if __name__ == '__main__':
#     evaluate_model('tweets_suspect_preprocessed.csv', 'model.pkl', 'tfidf_vectorizer.pkl', 'metrics.json')

!dvc stage add -n evaluate --force \
        -d tweets_suspect_preprocessed.csv \
        -d model.pkl \
        -d tfidf_vectorizer.pkl \
        -d evaluate.py \
        -M metrics.json \
        python evaluate.py

"""#### Visualisation et exécution du pipeline DVC

Maintenant que toutes les étapes sont définies, nous pouvons visualiser le graphe du pipeline et l'exécuter.
"""

!dvc dag

!dvc repro

"""###Reproductibilité

Le projet doit permettre à une autre personne de reproduire les résultats à l’aide des commandes :

dvc pull

dvc repro

### Reproduction du projet avec DVC

Pour reproduire le projet, il suffit d'utiliser les commandes `dvc pull` pour récupérer les données et les artefacts, puis `dvc repro` pour exécuter le pipeline.
"""

print("Pulling DVC tracked files...")
!dvc pull
print("DVC pull complete.")

print("Reproducing DVC pipeline...")
!dvc repro
print("DVC repro complete.")

"""### Vérification des métriques reproduites

Nous pouvons maintenant charger le fichier `metrics.json` pour vérifier que les métriques ont été reproduites avec succès.
"""

import json

with open('metrics.json', 'r') as f:
    reproduced_metrics = json.load(f)

display(reproduced_metrics)

"""#Partie 3 - Représentation des données

Transformer les tweets en représentations numériques.


Choisir au moins une des approches suivantes :

Approches classiques

*   Bag of Words


"""

from sklearn.feature_extraction.text import CountVectorizer

# Initialiser CountVectorizer
bow_vectorizer = CountVectorizer(max_features=5000) # You can adjust max_features as needed

# Ajuster et transformer les messages lemmatisés
X_bow = bow_vectorizer.fit_transform(df_pipeline['message_lemmatized'])

print("Dimensions de la matrice « sac de mots »:", X_bow.shape)

# Affichez quelques noms de caractéristiques (mots) pour voir ce que le vectoriseur a appris.
print("\nTop 100 features (words):")
print(bow_vectorizer.get_feature_names_out()[:100])

"""
*   TF-IDF

"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Initialiser TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=5000) # Tout comme pour le modèle « Bag of Words » (BoW), nous pouvons limiter les caractéristiques.

# Ajuster et transformer les messages lemmatisés
X_tfidf = tfidf_vectorizer.fit_transform(df_pipeline['message_lemmatized'])

print("Shape of TF-IDF matrix:", X_tfidf.shape)

# Affichez quelques noms de caractéristiques (mots) pour voir ce que le vectoriseur a appris.
print("\nTop 100 features (words):")
print(tfidf_vectorizer.get_feature_names_out()[:100])

"""Approches avancées


*   Word2Vec
"""

!pip install gensim

import gensim.models

# Tokeniser les messages lemmatisés pour l'entraînement de Word2Vec
# Word2Vec attend une liste de listes de mots
tokenized_messages = [message.split() for message in df_pipeline['message_lemmatized']]

# Entraîner le modèle Word2Vec
# Vous pouvez ajuster des paramètres tels que vector_size, window, min_count et workers
word2vec_model = gensim.models.Word2Vec(
    sentences=tokenized_messages,
    vector_size=100,  # Dimension des vecteurs de mots
    window=5,         # Taille de la fenêtre de contexte
    min_count=5,      # Ignore tous les mots dont la fréquence totale est inférieure à cette valeur.
    workers=4         # Nombre de cœurs de processeur
)

# Obtenir la taille du vocabulaire
vocab_size = len(word2vec_model.wv)
print(f"Word2Vec vocabulary size: {vocab_size}")

# Afficher le vecteur d'un mot exemple (par ex. « love ») s'il est présent dans le vocabulaire.
if 'love' in word2vec_model.wv:
    print("\nVector for 'love':")
    print(word2vec_model.wv['love'][:10]) # Afficher les 10 premières dimensions
else:
    print("\n'love' not found in Word2Vec vocabulary (min_count might be too high).")

"""*   GloVe

GloVe est un algorithme d'apprentissage non supervisé permettant d'obtenir des représentations vectorielles de mots. Il est entraîné à partir de statistiques globales de cooccurrence mot-mot issues d'un corpus. Les vecteurs sont appris en optimisant une fonction objectif qui vise à minimiser la différence entre le produit scalaire de deux vecteurs de mots et le logarithme de leur probabilité de cooccurrence.
"""

import gensim.downloader as api
import numpy as np

# Charger un modèle GloVe pré-entraîné (par exemple, 'glove-twitter-25' pour des vecteurs à 25 dimensions entraînés sur des données Twitter)
# Le téléchargement peut prendre un instant lors de la première utilisation.
print("Downloading GloVe model...")
glove_model = api.load("glove-twitter-25")
print("GloVe model loaded.")

# Fonction pour obtenir un vecteur de document en faisant la moyenne des vecteurs de motss
def get_glove_document_vector(words, model, vector_size):
    vector = np.zeros(vector_size)
    count = 0
    for word in words:
        if word in model:
            vector += model[word]
            count += 1
    if count > 0:
        vector /= count
    return vector

# Définir la taille du vecteur en fonction du modèle GloVe chargé
glove_vector_size = glove_model.vector_size

#Créer des plongements de document GloVe pour tous les messages.
X_glove = np.array([
    get_glove_document_vector(doc, glove_model, glove_vector_size)
    for doc in tokenized_messages
])

print("Shape of GloVe document embeddings matrix:", X_glove.shape)

# Afficher le premier vecteur de document (les 10 premières dimensions)
print("\nFirst GloVe document vector (first 10 dimensions):")
print(X_glove[0, :10])

"""
*   FastText

"""

!pip install fasttext

import fasttext
import numpy as np

# FastText s'attend à ce que le fichier texte d'entrée soit prétraité
# Enregistrons les messages tokenisés dans un fichier temporaire pour l'entraînement avec FastText
fasttext_input_path = 'fasttext_input.txt'
with open(fasttext_input_path, 'w') as f:
    for tokens in tokenized_messages:
        f.write(' '.join(tokens) + '\n')

print(f"Tokenized messages saved to {fasttext_input_path} for FastText training.")

import fasttext
import numpy as np

# FastText s'attend à ce que le fichier texte d'entrée soit prétraité
# Enregistrons les messages tokenisés dans un fichier temporaire pour l'entraînement avec FastText
fasttext_input_path = 'fasttext_input.txt'
with open(fasttext_input_path, 'w') as f:
    for tokens in tokenized_messages:
        f.write(' '.join(tokens) + '\n')

print(f"Tokenized messages saved to {fasttext_input_path} for FastText training.")

# Entraîner un modèle FastText
# Vous pouvez ajuster des paramètres tels que vector_size, minCount et ws (taille de la fenêtre)
# Définir minCount=1 pour s'assurer que tous les mots sont inclus pour cette démonstration
print("Training FastText model... (This may take some time)")
fasttext_model = fasttext.train_unsupervised(
    fasttext_input_path,
    model='skipgram', # 'skipgram' or 'cbow'
    dim=100,          # Dimension des vecteurs de mots
    minCount=1,       # Nombre minimal d'occurrences de mots pour être inclus dans le vocabulaire
    ws=5              # Taille de la fenêtre
)

print("FastText model trained.")

# Obtenir la taille du vocabulaire
vocab_size_fasttext = len(fasttext_model.words)
print(f"FastText vocabulary size: {vocab_size_fasttext}")

# Afficher le vecteur d'un mot exemple (par ex. « love »)
if 'love' in fasttext_model.words:
    print("\nVector for 'love':")
    print(fasttext_model.get_word_vector('love')[:10]) # Afficher les 10 premières dimensions
else:
    print("\n'love' not found in FastText vocabulary.")

# Fonction pour obtenir un vecteur de document en faisant la moyenne des vecteurs de mots pour FastText
def get_fasttext_document_vector(words, model, vector_size):
    vector = np.zeros(vector_size)
    count = 0
    for word in words:
        vector += model.get_word_vector(word)
        count += 1
    if count > 0:
        vector /= count
    return vector

# Définir la taille du vecteur en fonction du modèle FastText entraîné
fasttext_vector_size = fasttext_model.get_dimension()

# Créer des plongements de document FastText pour tous les messages
X_fasttext = np.array([
    get_fasttext_document_vector(doc, fasttext_model, fasttext_vector_size)
    for doc in tokenized_messages
])

print("Shape of FastText document embeddings matrix:", X_fasttext.shape)

# Afficher le premier vecteur de document (les 10 premières dimensions):
print("\nFirst FastText document vector (first 10 dimensions):")
print(X_fasttext[0, :10])

"""*   Sentence Transformers

### Sentence Transformers

Sentence Transformers (SBERT) est un framework Python destiné aux plongements (embeddings) de phrases, de textes et d'images. Il est conçu pour calculer des représentations vectorielles denses pour des phrases et des paragraphes. Ces modèles reposent sur des réseaux de type Transformer (tels que BERT, RoBERTa, etc.) et sont affinés pour produire des plongements sémantiquement significatifs, où les phrases ayant des sens similaires sont proches dans l'espace vectoriel. Cette approche est particulièrement efficace pour des tâches telles que la recherche sémantique, le regroupement (clustering) et la détection de paraphrases.
"""

!pip install -U sentence-transformers

from sentence_transformers import SentenceTransformer
import numpy as np

# Charger un modèle Sentence Transformer pré-entraîné
# « all-MiniLM-L6-v2 » offre un bon équilibre entre vitesse et performance
print("Loading Sentence Transformer model (all-MiniLM-L6-v2)...")
sbert_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Sentence Transformer model loaded.")

# Générer des plongements de phrases
# Le modèle attend une liste de chaînes de caractères
print("Generating Sentence Transformer embeddings... (This may take some time)")
X_sbert = sbert_model.encode(df_pipeline['message_lemmatized'].tolist())

print("Shape of Sentence Transformer embeddings matrix:", X_sbert.shape)

# Afficher le premier vecteur de document (les 10 premières dimensions)
print("\nFirst Sentence Transformer document vector (first 10 dimensions):")
print(X_sbert[0, :10])

"""*   BERT

### Régénération des Embeddings BERT (Correction de NameError)

Il semble que les embeddings BERT (`X_bert`) n'étaient pas disponibles lors de l'exécution précédente, entraînant une `NameError`. Pour corriger cela et s'assurer que les comparaisons de modèles soient complètes, nous allons régénérer les embeddings BERT avant de procéder à l'entraînement et à l'évaluation du modèle basé sur BERT.
"""

from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
import pandas as pd

# Load a pre-trained BERT tokenizer and model
# 'bert-base-uncased' is a commonly used model
print("Loading BERT tokenizer and model (bert-base-uncased)...")
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')
print("BERT tokenizer and model loaded.")

# Function to generate BERT embeddings for a list of texts
def get_bert_embeddings(texts, tokenizer, model, max_length=128):
    model.eval() # Set model to evaluation mode
    all_embeddings = []
    # Process texts in batches to reduce memory usage and speed up computation
    batch_size = 32 # You can adjust this batch size based on your available memory
    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i + batch_size]

        # Tokenize the batch of texts and convert to input IDs
        encoded_input = tokenizer(
            batch_texts,
            padding='max_length',
            truncation=True,
            max_length=max_length,
            return_tensors='pt' # Return PyTorch tensors
        )

        # Move tensors to the same device as the model (e.g., CPU or GPU if available)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        encoded_input = {k: v.to(device) for k, v in encoded_input.items()}
        model.to(device)

        with torch.no_grad(): # Disable gradient calculation for inference
            model_output = model(**encoded_input)

        # Get the embeddings of the [CLS] token (first token) as sentence embedding
        # You can also average the last_hidden_state output for all tokens
        sentence_embeddings = model_output.last_hidden_state[:, 0, :].cpu().numpy()
        all_embeddings.extend(sentence_embeddings)

    return np.array(all_embeddings)

# Ensure df_pipeline is available for labels
if 'df_pipeline' not in locals():
    try:
        df_pipeline = pd.read_csv('tweets_suspect_preprocessed.csv')
        df_pipeline['message_lemmatized'] = df_pipeline['message_lemmatized'].fillna('')
    except FileNotFoundError:
        raise FileNotFoundError("Preprocessed data file 'tweets_suspect_preprocessed.csv' not found.")

print("Generating BERT embeddings... (This may take some time)")
# Convert the 'message_lemmatized' series to a list for the function
X_bert = get_bert_embeddings(df_pipeline['message_lemmatized'].tolist(), tokenizer, model)

print("Shape of BERT embeddings matrix:", X_bert.shape)

# Display the first document vector (first 10 dimensions):
print("\nFirst BERT document vector (first 10 dimensions):")
print(X_bert[0, :10])

from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np

# Load a pre-trained BERT tokenizer and model
# 'bert-base-uncased' is a commonly used model
print("Loading BERT tokenizer and model (bert-base-uncased)...")
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')
print("BERT tokenizer and model loaded.")

# Function to generate BERT embeddings for a list of texts
def get_bert_embeddings(texts, tokenizer, model, max_length=128):
    model.eval() # Set model to evaluation mode
    all_embeddings = []
    # Process texts in batches to reduce memory usage and speed up computation
    batch_size = 32 # You can adjust this batch size based on your available memory
    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i + batch_size]

        # Tokenize the batch of texts and convert to input IDs
        encoded_input = tokenizer(
            batch_texts,
            padding='max_length',
            truncation=True,
            max_length=max_length,
            return_tensors='pt' # Return PyTorch tensors
        )

        # Move tensors to the same device as the model (e.g., CPU or GPU if available)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        encoded_input = {k: v.to(device) for k, v in encoded_input.items()}
        model.to(device)

        with torch.no_grad(): # Disable gradient calculation for inference
            model_output = model(**encoded_input)

        # Get the embeddings of the [CLS] token (first token) as sentence embedding
        # You can also average the last_hidden_state output for all tokens
        sentence_embeddings = model_output.last_hidden_state[:, 0, :].cpu().numpy()
        all_embeddings.extend(sentence_embeddings)

    return np.array(all_embeddings)

print("Generating BERT embeddings... (This may take some time)")
# Convert the 'message_lemmatized' series to a list for the function
X_bert = get_bert_embeddings(df_pipeline['message_lemmatized'].tolist(), tokenizer, model)

print("Shape of BERT embeddings matrix:", X_bert.shape)

# Display the first document vector (first 10 dimensions):
print("\nFirst BERT document vector (first 10 dimensions):")
print(X_bert[0, :10])

from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Ensure X_bert is available after running the BERT embedding generation cell
if 'X_bert' not in locals():
    raise NameError("X_bert not found. Please ensure the BERT embedding generation cell is run successfully.")

# Ensure df_pipeline is available for labels
if 'df_pipeline' not in locals():
    try:
        df_pipeline = pd.read_csv('tweets_suspect_preprocessed.csv')
        df_pipeline['message_lemmatized'] = df_pipeline['message_lemmatized'].fillna('')
    except FileNotFoundError:
        raise FileNotFoundError("Preprocessed data file 'tweets_suspect_preprocessed.csv' not found.")

y = df_pipeline['label']

print(f"Original BERT embeddings shape: {X_bert.shape}")

# 1. Reduce dimensionality with PCA to 50 components (to match other models)
n_components_bert = 50
pca_bert = PCA(n_components=n_components_bert, random_state=42)
X_bert_pca = pca_bert.fit_transform(X_bert)

print(f"BERT embeddings shape after PCA (to {n_components_bert} components): {X_bert_pca.shape}")

# 2. Apply SMOTE to handle class imbalance
print("\nOriginal class distribution:\n", y.value_counts())
smote_bert = SMOTE(random_state=42)
X_bert_resampled, y_bert_resampled = smote_bert.fit_resample(X_bert_pca, y)

print(f"\nResampled BERT data shape: X={X_bert_resampled.shape}, y={y_bert_resampled.shape}")
print("New class distribution after SMOTE:\n", y_bert_resampled.value_counts())

# 3. Split the resampled data into training and testing sets
X_train_bert, X_test_bert, y_train_bert, y_test_bert = train_test_split(
    X_bert_resampled, y_bert_resampled, test_size=0.2, random_state=42, stratify=y_bert_resampled
)

print("\nTraining Logistic Regression model with SMOTE-resampled BERT data...")

# 4. Train a Logistic Regression model
log_reg_bert_model = LogisticRegression(random_state=42, solver='liblinear', max_iter=1000)
log_reg_bert_model.fit(X_train_bert, y_train_bert)

print("Model training complete.")

# 5. Make predictions and evaluate the model
y_pred_bert = log_reg_bert_model.predict(X_test_bert)

# Calculate metrics
accuracy_bert = accuracy_score(y_test_bert, y_pred_bert)
report = classification_report(y_test_bert, y_pred_bert, output_dict=True)

# Extract precision and recall for weighted average
precision_bert = report['weighted avg']['precision']
recall_bert = report['weighted avg']['recall']

print(f"\nAccuracy (Logistic Regression on BERT embeddings): {accuracy_bert:.4f}")
print(f"Precision (Logistic Regression on BERT embeddings): {precision_bert:.4f}")
print(f"Recall (Logistic Regression on BERT embeddings): {recall_bert:.4f}") # Added this line
print("\nClassification Report (Logistic Regression on BERT embeddings):\n")
print(classification_report(y_test_bert, y_pred_bert))

# Plot Confusion Matrix
cm_bert = confusion_matrix(y_test_bert, y_pred_bert)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_bert, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Negative (0)', 'Positive (1)'],
            yticklabels=['Negative (0)', 'Positive (1)'])
plt.title('Confusion Matrix for Logistic Regression (BERT Embeddings + SMOTE)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Update the model_accuracies dictionary to include the BERT model's accuracy
if 'model_accuracies' in locals():
    model_accuracies['Logistic Regression (BERT+PCA+SMOTE)'] = accuracy_bert
else:
    model_accuracies = {'Logistic Regression (BERT+PCA+SMOTE)': accuracy_bert}

# You might also want to re-display the performance_df if you want the table updated immediately
# Create a DataFrame for comparison
performance_df = pd.DataFrame({
    'Model': list(model_accuracies.keys()),
    'Accuracy': list(model_accuracies.values())
}).sort_values(by='Accuracy', ascending=False)

display(performance_df)

"""### BERT (Bidirectional Encoder Representations from Transformers)

BERT est un modèle puissant de représentation du langage pré-entraîné, développé par Google. Contrairement aux méthodes traditionnelles de plongement de mots (*word embeddings*) telles que Word2Vec ou GloVe, BERT est bidirectionnel et contextuel. Cela signifie qu'il prend en compte le contexte d'un mot à la fois à gauche et à droite simultanément, et que la représentation vectorielle (le plongement) d'un mot varie en fonction de son contexte au sein de la phrase.

BERT peut être utilisé pour générer des représentations vectorielles pour des phrases entières ou des documents. Une approche courante pour obtenir des représentations de phrases consiste à utiliser la sortie associée au jeton [CLS] (qui agrège généralement les informations au niveau de la phrase) ou à calculer la moyenne des représentations de tous les jetons de la phrase.
"""

!pip install transformers torch

from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np

# Load a pre-trained BERT tokenizer and model
# 'bert-base-uncased' is a commonly used model
print("Loading BERT tokenizer and model (bert-base-uncased)...")
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')
print("BERT tokenizer and model loaded.")

# Function to generate BERT embeddings for a list of texts
def get_bert_embeddings(texts, tokenizer, model, max_length=128):
    model.eval() # Set model to evaluation mode
    all_embeddings = []
    # Process texts in batches to reduce memory usage and speed up computation
    batch_size = 32 # You can adjust this batch size based on your available memory
    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i + batch_size]

        # Tokenize the batch of texts and convert to input IDs
        encoded_input = tokenizer(
            batch_texts,
            padding='max_length',
            truncation=True,
            max_length=max_length,
            return_tensors='pt' # Return PyTorch tensors
        )

        # Move tensors to the same device as the model (e.g., CPU or GPU if available)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        encoded_input = {k: v.to(device) for k, v in encoded_input.items()}
        model.to(device)

        with torch.no_grad(): # Disable gradient calculation for inference
            model_output = model(**encoded_input)

        # Get the embeddings of the [CLS] token (first token) as sentence embedding
        # You can also average the last_hidden_state output for all tokens
        sentence_embeddings = model_output.last_hidden_state[:, 0, :].cpu().numpy()
        all_embeddings.extend(sentence_embeddings)

    return np.array(all_embeddings)

print("Generating BERT embeddings... (This may take some time)")
# Convert the 'message_lemmatized' series to a list for the function
X_bert = get_bert_embeddings(df_pipeline['message_lemmatized'].tolist(), tokenizer, model)

print("Shape of BERT embeddings matrix:", X_bert.shape)

# Display the first document vector (first 10 dimensions):
print("\nFirst BERT document vector (first 10 dimensions):")
print(X_bert[0, :10])

"""Justifier le choix retenu.

### Justification du choix de la représentation des données: Sentence Transformers

Pour la classification de tweets, le choix de la méthode de représentation des données est crucial pour la performance du modèle. Parmi les options explorées (Bag of Words, TF-IDF, Word2Vec, GloVe, FastText, BERT, Sentence Transformers), les **Sentence Transformers** (SBERT) se distinguent comme un excellent compromis pour plusieurs raisons clés:

1.  **Captures sémantiques contextuelles**: Contrairement aux approches plus simples comme BoW et TF-IDF qui ignorent l'ordre des mots et le contexte, ou aux embeddings statiques comme Word2Vec/GloVe qui attribuent un vecteur unique à chaque mot quelle que soit son utilisation, les SBERT génèrent des embeddings de phrases **contextuels**. Cela signifie qu'ils comprennent la signification de la phrase entière, ce qui est essentiel pour des tâches de classification basées sur le sens global, comme la détection de sentiments ou la classification thématique de tweets.

2.  **Performance pour les textes courts**: Les tweets sont par nature des textes courts. Les modèles BERT et SBERT sont particulièrement performants sur ce type de données car ils ont été pré-entraînés sur d'énormes corpus textuels et sont capables de saisir des nuances sémantiques importantes même avec un nombre limité de mots. SBERT est spécifiquement conçu pour produire des embeddings de qualité pour des phrases entières, ce qui est idéal pour les tweets.

3.  **Facilité d'utilisation pour les embeddings de phrases**: Bien que BERT puisse également être utilisé pour générer des embeddings de phrases (par exemple, en utilisant le token `[CLS]` ou en faisant la moyenne des tokens), SBERT est explicitement fine-tuné pour générer des embeddings de phrases de haute qualité qui peuvent être comparés directement (par exemple, via la similarité cosinus) avec une grande efficacité. Cela simplifie l'étape d'ingénierie des features et peut souvent conduire à de meilleures performances out-of-the-box.

4.  **Gestion des mots hors vocabulaire (OOD)**: En tant que modèles basés sur des Transformers, les SBERT gèrent mieux les mots hors vocabulaire (OOV) que les méthodes traditionnelles. Grâce à leur tokenisation sub-word (comme WordPiece ou BPE), ils peuvent construire des représentations pour des mots jamais vus en combinant des sous-mots connus.

En résumé, les Sentence Transformers offrent une représentation riche et sémantiquement pertinente des tweets, ce qui est fondamental pour construire un modèle de classification robuste et précis. Ils surmontent les limitations des méthodes plus anciennes en capturant le contexte et en étant particulièrement adaptés aux textes courts.

Optionnel

Appliquer une technique de réduction de dimension :


*   PCA
"""

from sklearn.decomposition import PCA
from sentence_transformers import SentenceTransformer
import numpy as np
import pandas as pd

# Load a pre-trained Sentence Transformer model if not already loaded
# 'all-MiniLM-L6-v2' is a good balance of speed and performance
print("Loading Sentence Transformer model (all-MiniLM-L6-v2)...")
sbert_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Sentence Transformer model loaded.")

# Load the preprocessed DataFrame which contains 'message_lemmatized'
try:
    df_pipeline = pd.read_csv('tweets_suspect_preprocessed.csv')
    # Ensure 'message_lemmatized' column exists and handle potential NaN values
    if 'message_lemmatized' not in df_pipeline.columns:
        raise ValueError("Column 'message_lemmatized' not found in preprocessed data.")
    df_pipeline['message_lemmatized'] = df_pipeline['message_lemmatized'].fillna('')
    print("Preprocessed data 'tweets_suspect_preprocessed.csv' loaded.")
except FileNotFoundError:
    raise FileNotFoundError("Preprocessed data file 'tweets_suspect_preprocessed.csv' not found. Please ensure data preprocessing steps are executed and the file is created.")
except Exception as e:
    raise ValueError(f"Error loading or processing preprocessed data: {e}")

print("Generating Sentence Transformer embeddings... (This may take some time)")
X_sbert = sbert_model.encode(df_pipeline['message_lemmatized'].tolist())
print("Sentence Transformer embeddings generated.")

# Initialize PCA to reduce dimensionality, e.g., to 50 components
# You can choose a different number of components or a percentage of variance to explain
n_components = 50
pca = PCA(n_components=n_components)

# Fit PCA on the Sentence Transformer embeddings and transform them
X_sbert_pca = pca.fit_transform(X_sbert)

print(f"Shape of Sentence Transformer embeddings after PCA (to {n_components} components):", X_sbert_pca.shape)

# Display the first document vector after PCA (first 10 dimensions)
print("\nFirst PCA-reduced SBERT document vector (first 10 dimensions):")
print(X_sbert_pca[0, :10])

"""*   t-SNE


"""

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns

# t-SNE is computationally intensive, especially for large datasets.
# It's common practice to apply it to a smaller subset or to data already reduced by PCA.
# We will sample 2000 data points for demonstration.

# Ensure X_sbert_pca is available
if 'X_sbert_pca' not in locals():
    raise NameError("X_sbert_pca not found. Please run the PCA cell first.")

# For visualization, typically 2 or 3 components are used.
# Let's take a random sample to speed up computation for demonstration.
sample_size = min(2000, X_sbert_pca.shape[0]) # Use at most 2000 samples
np.random.seed(42) # for reproducibility
sample_indices = np.random.choice(X_sbert_pca.shape[0], sample_size, replace=False)
X_sbert_pca_sample = X_sbert_pca[sample_indices]
y_sample = df_pipeline['label'].iloc[sample_indices]

print(f"Applying t-SNE on a sample of {sample_size} data points...")

# Initialize t-SNE
# perplexity can be between 5 and 50. learning_rate can be between 10 and 1000.
# n_iter_early_exaggeration: 250, n_iter: 3000 are default recommended values
tsne = TSNE(
    n_components=2,
    random_state=42,
    perplexity=30, # A common value, adjust based on data density
    learning_rate=200, # A common value, adjust based on data scale
    n_iter=1000 # Number of iterations, more iterations means more time
)

# Fit and transform the PCA-reduced sample
X_tsne = tsne.fit_transform(X_sbert_pca_sample)

print("Shape of t-SNE output:", X_tsne.shape)

# Display the first document vector after t-SNE (2 dimensions)
print("\nFirst t-SNE transformed document vector:")
print(X_tsne[0])

"""### Visualisation des embeddings avec t-SNE

Le t-Distributed Stochastic Neighbor Embedding (t-SNE) est une technique de réduction de dimension non linéaire particulièrement bien adaptée à la visualisation d'ensembles de données de haute dimension. Il projette les points de données dans un espace de dimension inférieure (généralement 2 ou 3) de manière à préserver les similarités entre les points : les points similaires dans l'espace de haute dimension restent proches les uns des autres dans l'espace de basse dimension, et les points dissemblables restent éloignés.

Contrairement à la PCA qui se concentre sur la préservation de la variance globale, le t-SNE excelle à révéler les structures de clustering locales et les relations entre les points de données. Il est souvent utilisé pour explorer visuellement la présence de clusters naturels dans les données, ce qui peut être très utile pour comprendre la distribution de vos embeddings de tweets.

En appliquant t-SNE sur les embeddings réduits par PCA, nous pouvons obtenir une représentation visuelle de la façon dont les tweets se regroupent en fonction de leur contenu sémantique, potentiellement révélant des patterns liés aux labels de sentiment (positif/négatif) ou à d'autres caractéristiques latentes.
"""

plt.figure(figsize=(10, 8))
sns.scatterplot(
    x=X_tsne[:, 0], y=X_tsne[:, 1],
    hue=y_sample,
    palette=sns.color_palette("hls", 2), # Assuming 2 classes (0 and 1)
    legend="full",
    alpha=0.7
)
plt.title('t-SNE Visualization of SBERT Embeddings (Sampled)')
plt.xlabel('t-SNE Component 1')
plt.ylabel('t-SNE Component 2')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""

*   UMAP

"""

!pip install umap-learn

import umap
import matplotlib.pyplot as plt
import seaborn as sns

# Ensure X_sbert_pca_sample and y_sample are available from the t-SNE step
if 'X_sbert_pca_sample' not in locals() or 'y_sample' not in locals():
    raise NameError("X_sbert_pca_sample or y_sample not found. Please run the t-SNE cell or previous cells first.")

print(f"Applying UMAP on the same sample of {X_sbert_pca_sample.shape[0]} data points...")

# Initialize UMAP
# n_components: number of dimensions for the reduced space (usually 2 for visualization)
# n_neighbors: controls how UMAP balances local versus global structure (smaller values emphasize local structure)
# min_dist: controls how tightly clustered points are allowed to be
umap_reducer = umap.UMAP(
    n_components=2,
    n_neighbors=15, # Default value, can be tuned
    min_dist=0.1,   # Default value, can be tuned
    random_state=42 # for reproducibility
)

# Fit and transform the PCA-reduced sample
X_umap = umap_reducer.fit_transform(X_sbert_pca_sample)

print("Shape of UMAP output:", X_umap.shape)

# Display the first document vector after UMAP (2 dimensions)
print("\nFirst UMAP transformed document vector:")
print(X_umap[0])

"""### Visualisation des embeddings avec UMAP

UMAP (Uniform Manifold Approximation and Projection) est une technique de réduction de dimension non linéaire. Comme t-SNE, UMAP est excellent pour la visualisation de données de haute dimension dans un espace 2D ou 3D. Cependant, UMAP est souvent préféré pour plusieurs raisons :

1.  **Vitesse et Scalabilité**: UMAP est généralement plus rapide que t-SNE, surtout sur de grands ensembles de données, et est plus scalable.
2.  **Préservation de la Structure Globale**: Contrairement à t-SNE qui est très bon pour préserver la structure locale mais peut parfois déformer la structure globale, UMAP tente de préserver à la fois la structure locale et globale de l'ensemble de données.
3.  **Théorie Mathématique**: UMAP est fondé sur une théorie mathématique plus solide (topologie algébrique) que t-SNE, ce qui peut rendre ses résultats plus stables et interprétables dans certains cas.

En appliquant UMAP, nous cherchons à obtenir une autre perspective sur la structure des embeddings de nos tweets, potentiellement avec une meilleure préservation des relations inter-clusters et une image plus claire de la distribution des labels de sentiment.
"""

plt.figure(figsize=(10, 8))
sns.scatterplot(
    x=X_umap[:, 0], y=X_umap[:, 1],
    hue=y_sample,
    palette=sns.color_palette("hls", 2), # Assuming 2 classes (0 and 1)
    legend="full",
    alpha=0.7
)
plt.title('UMAP Visualization of SBERT Embeddings (Sampled)')
plt.xlabel('UMAP Component 1')
plt.ylabel('UMAP Component 2')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""#Partie 4 - Construction des modèles

Gestion du déséquilibre des classes

Tester au moins une stratégie parmi :

*   Oversampling (SMOTE)


"""

from imblearn.over_sampling import SMOTE
import pandas as pd
import numpy as np

# Ensure df_pipeline and X_sbert_pca are available
# We'll re-load df_pipeline to get the labels correctly aligned if not already in scope
if 'df_pipeline' not in locals():
    try:
        df_pipeline = pd.read_csv('tweets_suspect_preprocessed.csv')
        df_pipeline['message_lemmatized'] = df_pipeline['message_lemmatized'].fillna('')
    except FileNotFoundError:
        raise FileNotFoundError("Preprocessed data file 'tweets_suspect_preprocessed.csv' not found.")

# If X_sbert_pca is not already in the kernel, we would need to regenerate it.
# Assuming X_sbert_pca from previous steps is correctly in the kernel state.

# Define features (X) and target (y)
X = X_sbert_pca # Use the PCA-reduced SBERT embeddings as features
y = df_pipeline['label']

print(f"Original dataset shape: X={X.shape}, y={y.shape}")
print("Original class distribution:\n", y.value_counts())

# Initialize SMOTE
smote = SMOTE(random_state=42)

# Apply SMOTE to the training data
X_resampled, y_resampled = smote.fit_resample(X, y)

print(f"\nResampled dataset shape: X={X_resampled.shape}, y={y_resampled.shape}")
print("New class distribution:\n", y_resampled.value_counts())

"""

*    Undersampling

"""

from imblearn.under_sampling import RandomUnderSampler
import pandas as pd
import numpy as np

# Ensure df_pipeline and X_sbert_pca are available (re-load if necessary, similar to SMOTE cell)
if 'df_pipeline' not in locals():
    try:
        df_pipeline = pd.read_csv('tweets_suspect_preprocessed.csv')
        df_pipeline['message_lemmatized'] = df_pipeline['message_lemmatized'].fillna('')
    except FileNotFoundError:
        raise FileNotFoundError("Preprocessed data file 'tweets_suspect_preprocessed.csv' not found.")

# Assuming X_sbert_pca from previous steps is correctly in the kernel state.

# Define features (X) and target (y)
X = X_sbert_pca # Use the PCA-reduced SBERT embeddings as features
y = df_pipeline['label']

print(f"Original dataset shape: X={X.shape}, y={y.shape}")
print("Original class distribution:\n", y.value_counts())

# Initialize RandomUnderSampler
rus = RandomUnderSampler(random_state=42)

# Apply undersampling
X_undersampled, y_undersampled = rus.fit_resample(X, y)

print(f"\nUndersampled dataset shape: X={X_undersampled.shape}, y={y_undersampled.shape}")
print("New class distribution after undersampling:\n", y_undersampled.value_counts())

"""

*   Class Weights
"""

from sklearn.utils import class_weight
import numpy as np

# Ensure df_pipeline is available and contains the 'label' column
if 'df_pipeline' not in locals():
    try:
        df_pipeline = pd.read_csv('tweets_suspect_preprocessed.csv')
        df_pipeline['message_lemmatized'] = df_pipeline['message_lemmatized'].fillna('')
    except FileNotFoundError:
        raise FileNotFoundError("Preprocessed data file 'tweets_suspect_preprocessed.csv' not found.")

# Get the labels from the original dataset
y_original = df_pipeline['label']

# Calculate class weights
# 'balanced' mode automatically calculates weights inversely proportional to class frequencies
class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_original),
    y=y_original
)

# Convert to a dictionary for easier use with some models (e.g., Keras/TensorFlow)
class_weights_dict = dict(zip(np.unique(y_original), class_weights))

print("Original class distribution:\n", y_original.value_counts())
print("\nCalculated class weights:\n", class_weights_dict)

"""Comparaison des modèles

Évaluer au minimum trois algorithmes différents parmi :


*   Logistic Regression


"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Split the SMOTE-resampled data into training and testing sets
# Assuming X_resampled and y_resampled are available from the SMOTE cell
if 'X_resampled' not in locals() or 'y_resampled' not in locals():
    raise NameError("X_resampled or y_resampled not found. Please run the SMOTE cell first.")

X_train_smote, X_test_smote, y_train_smote, y_test_smote = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)

print("Training Logistic Regression model with SMOTE data...")

# Initialize and train the Logistic Regression model
# Using class_weights='balanced' is generally not needed after SMOTE, but can be used for other datasets
log_reg_model = LogisticRegression(random_state=42, solver='liblinear', max_iter=1000)
log_reg_model.fit(X_train_smote, y_train_smote)

print("Model training complete.")

# Make predictions on the test set
y_pred_smote = log_reg_model.predict(X_test_smote)

# Evaluate the model
accuracy = accuracy_score(y_test_smote, y_pred_smote)
print(f"\nAccuracy: {accuracy:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test_smote, y_pred_smote))

# Plot Confusion Matrix
cm = confusion_matrix(y_test_smote, y_pred_smote)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Negative (0)', 'Positive (1)'],
            yticklabels=['Negative (0)', 'Positive (1)'])
plt.title('Confusion Matrix for Logistic Regression (SMOTE Data)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""*   Naive Bayes



"""

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming X_train_smote, X_test_smote, y_train_smote, y_test_smote are available from previous splits
if 'X_train_smote' not in locals():
    raise NameError("SMOTE data split not found. Please run the Logistic Regression cell first or ensure SMOTE data is available.")

print("Training Naive Bayes model with SMOTE data...")

# Initialize and train the Gaussian Naive Bayes model
naive_bayes_model = GaussianNB()
naive_bayes_model.fit(X_train_smote, y_train_smote)

print("Model training complete.")

# Make predictions on the test set
y_pred_nb_smote = naive_bayes_model.predict(X_test_smote)

# Evaluate the model
accuracy_nb = accuracy_score(y_test_smote, y_pred_nb_smote)
print(f"\nAccuracy (Naive Bayes): {accuracy_nb:.4f}")

print("\nClassification Report (Naive Bayes):\n")
print(classification_report(y_test_smote, y_pred_nb_smote))

# Plot Confusion Matrix
cm_nb = confusion_matrix(y_test_smote, y_pred_nb_smote)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_nb, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Negative (0)', 'Positive (1)'],
            yticklabels=['Negative (0)', 'Positive (1)'])
plt.title('Confusion Matrix for Naive Bayes (SMOTE Data)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""*   SVM

### Support Vector Machine (SVM)

Les machines à vecteurs de support (SVM) sont des modèles d'apprentissage supervisé puissants utilisés pour des tâches de classification et de régression. Le principe fondamental des SVM consiste à trouver un hyperplan optimal qui sépare au mieux les points de données appartenant à différentes classes dans un espace de caractéristiques de grande dimension.

Pour des données linéairement séparables, le SVM cherche l'hyperplan maximisant la distance par rapport au point d'entraînement le plus proche (quelle que soit la classe), distance appelée « marge ». Une marge plus large conduit généralement à une erreur de généralisation plus faible.

Pour des données non linéairement séparables, les SVM utilisent une technique appelée « astuce du noyau » (kernel trick) pour projeter les données dans un espace de caractéristiques de dimension supérieure, où une séparation linéaire peut s'avérer possible. Parmi les fonctions de noyau courantes, on trouve les noyaux linéaires, polynomiaux, à base radiale (RBF) et sigmoïdes.

Dans ce cas, compte tenu de la réduction de dimensionnalité effectuée par ACP, un noyau linéaire (implémenté efficacement par LinearSVC) constitue souvent un bon point de départ, grâce à son équilibre entre performance et coût de calcul.
"""

from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming X_train_smote, X_test_smote, y_train_smote, y_test_smote are available from previous splits
if 'X_train_smote' not in locals():
    raise NameError("SMOTE data split not found. Please run the Logistic Regression cell first or ensure SMOTE data is available.")

print("Training Linear SVC model with SMOTE data...")

# Initialize and train the LinearSVC model
# LinearSVC is suitable for large datasets and uses a linear kernel.
# Setting max_iter to prevent convergence warnings for some datasets.
svm_model = LinearSVC(random_state=42, dual=False, max_iter=2000) # Set dual=False for n_samples > n_features
svm_model.fit(X_train_smote, y_train_smote)

print("Model training complete.")

# Make predictions on the test set
y_pred_svm_smote = svm_model.predict(X_test_smote)

# Evaluate the model
accuracy_svm = accuracy_score(y_test_smote, y_pred_svm_smote)
print(f"\nAccuracy (Linear SVC): {accuracy_svm:.4f}")

print("\nClassification Report (Linear SVC):\n")
print(classification_report(y_test_smote, y_pred_svm_smote))

# Plot Confusion Matrix
cm_svm = confusion_matrix(y_test_smote, y_pred_svm_smote)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_svm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Negative (0)', 'Positive (1)'],
            yticklabels=['Negative (0)', 'Positive (1)'])
plt.title('Confusion Matrix for Linear SVC (SMOTE Data)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""*   Random Forest

### Random Forest Classifier

La forêt aléatoire (Random Forest) est une méthode d'apprentissage d'ensemble qui fonctionne en construisant une multitude d'arbres de décision lors de la phase d'entraînement. Pour les tâches de classification, le résultat fourni par la forêt aléatoire correspond à la classe choisie par la majorité des arbres.

Caractéristiques et avantages clés de la forêt aléatoire :

Apprentissage d'ensemble : Il s'agit d'un type d'algorithme de *bagging* qui réduit la variance et prévient le surapprentissage en combinant les prédictions de plusieurs arbres de décision individuels.

Robustesse face au surapprentissage : Chaque arbre de la forêt est entraîné sur un sous-ensemble aléatoire des données d'entraînement (via la technique du *bootstrapping*) et ne prend en compte qu'un sous-ensemble aléatoire de caractéristiques pour effectuer les divisions à chaque nœud. Cette double dimension aléatoire contribue à réduire le surapprentissage.

Gestion de la haute dimensionnalité : L'algorithme est performant même avec un grand nombre de caractéristiques et est moins sensible au « fléau de la dimensionnalité » que certains autres algorithmes.

Importance des caractéristiques : Les forêts aléatoires permettent également d'évaluer l'importance des caractéristiques, en indiquant lesquelles ont le plus contribué à la prédiction.

Nous entraînerons un `RandomForestClassifier` sur les données rééchantillonnées par la méthode SMOTE afin d'évaluer ses performances par rapport aux modèles précédemment testés.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming X_train_smote, X_test_smote, y_train_smote, y_test_smote are available from previous splits
if 'X_train_smote' not in locals():
    raise NameError("SMOTE data split not found. Please run the Logistic Regression cell first or ensure SMOTE data is available.")

print("Training Random Forest Classifier model with SMOTE data...")

# Initialize and train the RandomForestClassifier model
# n_estimators: number of trees in the forest
# random_state: for reproducibility
# You can tune other parameters like max_depth, min_samples_leaf, etc.
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1) # n_jobs=-1 uses all available cores
rf_model.fit(X_train_smote, y_train_smote)

print("Model training complete.")

# Make predictions on the test set
y_pred_rf_smote = rf_model.predict(X_test_smote)

# Evaluate the model
accuracy_rf = accuracy_score(y_test_smote, y_pred_rf_smote)
print(f"\nAccuracy (Random Forest): {accuracy_rf:.4f}")

print("\nClassification Report (Random Forest):\n")
print(classification_report(y_test_smote, y_pred_rf_smote))

# Plot Confusion Matrix
cm_rf = confusion_matrix(y_test_smote, y_pred_rf_smote)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Negative (0)', 'Positive (1)'],
            yticklabels=['Negative (0)', 'Positive (1)'])
plt.title('Confusion Matrix for Random Forest (SMOTE Data)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""*   XGBoos

### XGBoost Classifier

XGBoost (eXtreme Gradient Boosting) est une bibliothèque open source très performante et populaire qui fournit un framework de gradient boosting pour C++, Java, Python, R et Julia. Conçu pour offrir une grande extensibilité, il est souvent considéré comme un algorithme d'apprentissage automatique de pointe pour les données structurées.

Principales caractéristiques et avantages de XGBoost :

Gradient Boosting : Il s'agit d'une méthode d'apprentissage d'ensemble dans laquelle de nouveaux modèles sont ajoutés séquentiellement pour corriger les erreurs des modèles précédents. Cette technique combine des modèles faibles (généralement des arbres de décision) pour former un modèle fort.

Régularisation : XGBoost intègre des termes de régularisation (L1 et L2) pour prévenir le surapprentissage, favorisant ainsi une bonne généralisation aux données inédites.

Gestion des valeurs manquantes : Il dispose d'une fonctionnalité intégrée pour gérer les valeurs manquantes en apprenant la meilleure direction à adopter pour celles-ci.

Traitement parallèle : XGBoost est optimisé pour le traitement parallèle, ce qui lui permet d'entraîner des modèles beaucoup plus rapidement que les implémentations traditionnelles de gradient boosting.
Flexibilité : Il prend en charge diverses fonctions objectif, notamment pour la régression, la classification (binaire et multiclasse) et le classement (ranking).

Nous entraînerons un XGBClassifier sur les données rééchantillonnées par SMOTE afin de comparer ses performances avec celles des autres modèles.
"""

import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming X_train_smote, X_test_smote, y_train_smote, y_test_smote are available from previous splits
if 'X_train_smote' not in locals():
    raise NameError("SMOTE data split not found. Please run the Logistic Regression cell first or ensure SMOTE data is available.")

print("Training XGBoost Classifier model with SMOTE data...")

# Initialize and train the XGBClassifier model
# n_estimators: number of boosting rounds
# objective: 'binary:logistic' for binary classification
# eval_metric: 'logloss' is a good metric for classification
# use_label_encoder=False and enable_categorical=True to avoid future warnings
# random_state for reproducibility
xgb_model = xgb.XGBClassifier(
    n_estimators=100,
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False,
    random_state=42,
    n_jobs=-1 # Use all available cores
)
xgb_model.fit(X_train_smote, y_train_smote)

print("Model training complete.")

# Make predictions on the test set
y_pred_xgb_smote = xgb_model.predict(X_test_smote)

# Evaluate the model
accuracy_xgb = accuracy_score(y_test_smote, y_pred_xgb_smote)
print(f"\nAccuracy (XGBoost): {accuracy_xgb:.4f}")

print("\nClassification Report (XGBoost):\n")
print(classification_report(y_test_smote, y_pred_xgb_smote))

# Plot Confusion Matrix
cm_xgb = confusion_matrix(y_test_smote, y_pred_xgb_smote)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_xgb, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Negative (0)', 'Positive (1)'],
            yticklabels=['Negative (0)', 'Positive (1)'])
plt.title('Confusion Matrix for XGBoost (SMOTE Data)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""*   LSTM

### Long Short-Term Memory (LSTM) Network

Les réseaux LSTM (*Long Short-Term Memory*) constituent un type particulier de réseaux de neurones récurrents (RNN) capables d'apprendre des dépendances à long terme. Ils ont été introduits pour remédier au problème de disparition du gradient qui affecte les RNN traditionnels, leur permettant ainsi de mémoriser efficacement des informations sur de longues périodes.

Caractéristiques clés des LSTM :

Cellules de mémoire : Les LSTM intègrent des « cellules de mémoire » capables de conserver leur état au fil du temps.
Il est possible d'écrire des informations dans ces cellules, de les y lire ou de les y effacer grâce à des portes spécifiques.

Portes : Les LSTM utilisent trois types principaux de portes pour contrôler le flux d'informations :
Porte d'oubli (*Forget Gate*) : Détermine quelles informations doivent être supprimées de l'état de la cellule.
Porte d'entrée (*Input Gate*) : Détermine quelles nouvelles informations doivent être stockées dans l'état de la cellule.

Porte de sortie (*Output Gate*) : Détermine quelle partie de l'état de la cellule doit être transmise en sortie.

Traitement de données séquentielles : Les LSTM sont particulièrement adaptés au traitement, à la classification et à la prédiction à partir de séries temporelles, de séquences de données et de textes non structurés.

Bien qu'ils soient généralement utilisés avec des séquences de plongements lexicaux (*word embeddings*), ils peuvent également s'adapter à des vecteurs de caractéristiques de taille fixe en les traitant comme une séquence d'un seul pas de temps.

Pour notre tâche, nous allons concevoir un classifieur simple basé sur un LSTM. Nous injecterons les plongements SBERT (réduits par ACP) dans la couche LSTM, en traitant chaque vecteur de 50 dimensions comme un pas de temps unique. Cela permet au réseau de potentiellement saisir des motifs complexes au sein de ces représentations denses.
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Ensure X_train_smote, X_test_smote, y_train_smote, y_test_smote are available
if 'X_train_smote' not in locals() or 'y_train_smote' not in locals():
    raise NameError("SMOTE data split not found. Please run the Logistic Regression cell first or ensure SMOTE data is available.")

print("Preparing data for LSTM...")

# LSTM expects input in the shape (samples, timesteps, features)
# Our X_train_smote and X_test_smote are (samples, 50)
# We can reshape them to (samples, 1, 50), treating each embedding as a single timestep.

X_train_lstm = X_train_smote.reshape(X_train_smote.shape[0], 1, X_train_smote.shape[1])
X_test_lstm = X_test_smote.reshape(X_test_smote.shape[0], 1, X_test_smote.shape[1])

print(f"Reshaped X_train for LSTM: {X_train_lstm.shape}")
print(f"Reshaped X_test for LSTM: {X_test_lstm.shape}")

print("Building LSTM model...")

# Define the LSTM model
model_lstm = Sequential([
    LSTM(128, activation='tanh', input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2])),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid') # Binary classification
])

# Compile the model
model_lstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model_lstm.summary()

print("Training LSTM model with SMOTE data...")

# Train the model
history = model_lstm.fit(
    X_train_lstm, y_train_smote,
    epochs=10, # Number of epochs can be tuned
    batch_size=32, # Batch size can be tuned
    validation_split=0.2, # Use a portion of training data for validation during training
    verbose=1
)

print("Model training complete.")

# Make predictions on the test set
y_pred_proba_lstm = model_lstm.predict(X_test_lstm)
y_pred_lstm = (y_pred_proba_lstm > 0.5).astype(int)

# Evaluate the model
accuracy_lstm = accuracy_score(y_test_smote, y_pred_lstm)
print(f"\nAccuracy (LSTM): {accuracy_lstm:.4f}")

print("\nClassification Report (LSTM):\n")
print(classification_report(y_test_smote, y_pred_lstm))

# Plot Confusion Matrix
cm_lstm = confusion_matrix(y_test_smote, y_pred_lstm)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_lstm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Negative (0)', 'Positive (1)'],
            yticklabels=['Negative (0)', 'Positive (1)'])
plt.title('Confusion Matrix for LSTM (SMOTE Data)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""*   BERT

### Évaluation d'un classificateur sur les embeddings BERT

Pour évaluer le modèle BERT dans notre cadre de comparaison, nous allons utiliser les *embeddings* générés par BERT (`X_bert`), réduire leur dimensionnalité avec PCA pour correspondre aux autres modèles (50 dimensions), puis appliquer SMOTE pour gérer le déséquilibre des classes avant d'entraîner un classificateur simple (comme la Régression Logistique) et d'évaluer ses performances.
"""

from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Ensure X_bert is available after running the BERT embedding generation cell
if 'X_bert' not in locals():
    raise NameError("X_bert not found. Please ensure the BERT embedding generation cell is run successfully.")

# Ensure df_pipeline is available for labels
if 'df_pipeline' not in locals():
    try:
        df_pipeline = pd.read_csv('tweets_suspect_preprocessed.csv')
        df_pipeline['message_lemmatized'] = df_pipeline['message_lemmatized'].fillna('')
    except FileNotFoundError:
        raise FileNotFoundError("Preprocessed data file 'tweets_suspect_preprocessed.csv' not found.")

y = df_pipeline['label']

print(f"Original BERT embeddings shape: {X_bert.shape}")

# 1. Reduce dimensionality with PCA to 50 components (to match other models)
n_components_bert = 50
pca_bert = PCA(n_components=n_components_bert, random_state=42)
X_bert_pca = pca_bert.fit_transform(X_bert)

print(f"BERT embeddings shape after PCA (to {n_components_bert} components): {X_bert_pca.shape}")

# 2. Apply SMOTE to handle class imbalance
print("\nOriginal class distribution:\n", y.value_counts())
smote_bert = SMOTE(random_state=42)
X_bert_resampled, y_bert_resampled = smote_bert.fit_resample(X_bert_pca, y)

print(f"\nResampled BERT data shape: X={X_bert_resampled.shape}, y={y_bert_resampled.shape}")
print("New class distribution after SMOTE:\n", y_bert_resampled.value_counts())

# 3. Split the resampled data into training and testing sets
X_train_bert, X_test_bert, y_train_bert, y_test_bert = train_test_split(
    X_bert_resampled, y_bert_resampled, test_size=0.2, random_state=42, stratify=y_bert_resampled
)

print("\nTraining Logistic Regression model with SMOTE-resampled BERT data...")

# 4. Train a Logistic Regression model
log_reg_bert_model = LogisticRegression(random_state=42, solver='liblinear', max_iter=1000)
log_reg_bert_model.fit(X_train_bert, y_train_bert)

print("Model training complete.")

# 5. Make predictions and evaluate the model
y_pred_bert = log_reg_bert_model.predict(X_test_bert)

# Calculate metrics
accuracy_bert = accuracy_score(y_test_bert, y_pred_bert)
report = classification_report(y_test_bert, y_pred_bert, output_dict=True)

# Extract precision and recall for weighted average
precision_bert = report['weighted avg']['precision']
recall_bert = report['weighted avg']['recall']

print(f"\nAccuracy (Logistic Regression on BERT embeddings): {accuracy_bert:.4f}")
print(f"Precision (Logistic Regression on BERT embeddings): {precision_bert:.4f}")
print(f"Recall (Logistic Regression on BERT embeddings): {recall_bert:.4f}") # Added this line
print("\nClassification Report (Logistic Regression on BERT embeddings):\n")
print(classification_report(y_test_bert, y_pred_bert))

# Plot Confusion Matrix
cm_bert = confusion_matrix(y_test_bert, y_pred_bert)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_bert, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Negative (0)', 'Positive (1)'],
            yticklabels=['Negative (0)', 'Positive (1)'])
plt.title('Confusion Matrix for Logistic Regression (BERT Embeddings + SMOTE)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""Comparer leurs performances

## Comparaison des performances des modèles

Nous allons maintenant récapituler et comparer les performances (précision) de tous les modèles que nous avons entraînés et évalués.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Collect accuracy scores from previously run models
# If X_bert evaluation was successful, accuracy_bert would be available.
# For now, we assume it might not be available and will handle it.

model_accuracies = {
    'Logistic Regression (SBERT+PCA+SMOTE)': accuracy,
    'Naive Bayes (SBERT+PCA+SMOTE)': accuracy_nb,
    'Linear SVC (SBERT+PCA+SMOTE)': accuracy_svm,
    'Random Forest (SBERT+PCA+SMOTE)': accuracy_rf,
    'XGBoost (SBERT+PCA+SMOTE)': accuracy_xgb,
    'LSTM (SBERT+PCA+SMOTE)': accuracy_lstm,
}

# Try to add BERT's Logistic Regression accuracy if available
if 'accuracy_bert' in locals():
    model_accuracies['Logistic Regression (BERT+PCA+SMOTE)'] = accuracy_bert
else:
    print("Note: BERT's Logistic Regression accuracy is not available. Please ensure the BERT embedding generation and evaluation cells were run successfully.")
    # Optionally, you can add a placeholder or exclude it if not available
    model_accuracies['Logistic Regression (BERT+PCA+SMOTE)'] = np.nan # Use NaN as placeholder

# Create a DataFrame for comparison
performance_df = pd.DataFrame({
    'Model': list(model_accuracies.keys()),
    'Accuracy': list(model_accuracies.values())
}).sort_values(by='Accuracy', ascending=False)

display(performance_df)

# Visualize the comparison
plt.figure(figsize=(12, 7))
sns.barplot(x='Accuracy', y='Model', data=performance_df, palette='viridis')
plt.title('Comparaison des Accuracies des Modèles de Classification')
plt.xlabel('Accuracy')
plt.ylabel('Modèle')
plt.xlim(0, 1) # Accuracy ranges from 0 to 1
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## Documentation des choix de modèles et de traitement des données

### 1. Représentation des données et prétraitement

**Choix effectué:** Les embeddings **Sentence Transformers (SBERT)**, réduits via une **Analyse en Composantes Principales (PCA)** à 50 dimensions, ont été choisis comme méthode principale de représentation des données. Une stratégie d'**oversampling (SMOTE)** a été appliquée pour gérer le déséquilibre des classes.

**Justification:**
*   **SBERT:** Cette méthode est excellente pour capturer le contexte sémantique des tweets, même courts. Contrairement à des approches comme TF-IDF ou Word2Vec, SBERT génère des embeddings de phrases qui représentent le sens global, ce qui est crucial pour les tâches de classification basées sur le sentiment. Il surpasse souvent BERT pour la génération d'embeddings de phrases en termes de qualité et d'efficacité.
*   **PCA:** La réduction de la dimensionalité par PCA permet de compresser les embeddings SBERT de haute dimension (souvent 384 ou 768 dimensions) en un espace de plus faible dimension (ici, 50). Cela réduit le bruit, améliore l'efficacité computationnelle des modèles en aval et aide à prévenir le surapprentissage, tout en conservant une grande partie de l'information pertinente.
*   **SMOTE:** La distribution originale des labels était très déséquilibrée (53855 positifs vs 6145 négatifs). SMOTE (Synthetic Minority Over-sampling Technique) a été utilisé pour générer des échantillons synthétiques de la classe minoritaire, équilibrant ainsi le jeu de données et permettant aux modèles d'apprendre de manière plus efficace sur les deux classes. Sans cette technique, les modèles auraient tendance à être biaisés envers la classe majoritaire.

### 2. Sélection du modèle de classification

**Choix effectué:** Le modèle de **Random Forest (SBERT+PCA+SMOTE)** a été sélectionné comme le plus performant.

**Justification:**
*   **Précision supérieure:** Le Random Forest a atteint une précision de **0.9505**, surpassant significativement les autres modèles testés, notamment la Régression Logistique (0.6945), Naive Bayes (0.7345), Linear SVC (0.6952), XGBoost (0.8680) et LSTM (0.8059).
*   **Robustesse:** Les forêts aléatoires sont des modèles d'ensemble robustes, moins sensibles au surapprentissage que les arbres de décision individuels. Elles gèrent bien la complexité des données et sont moins affectées par les valeurs aberrantes.
*   **Gestion des données complexes:** En combinant les avantages des embeddings SBERT et de la réduction de dimension par PCA, le Random Forest a démontré sa capacité à extraire des patterns complexes pour une classification précise.
*   **Classes équilibrées:** L'application de SMOTE avant l'entraînement a permis au Random Forest de performer de manière équitable sur les deux classes, sans être biaisé par la majorité.

**Note sur BERT:** Bien que BERT soit une approche avancée, la `NameError` rencontrée précédemment a pu limiter l'évaluation complète de sa performance par rapport aux autres modèles. Cependant, même si les embeddings BERT étaient correctement générés, l'efficacité de SBERT, spécifiquement pré-entraîné pour des embeddings de phrases, offre souvent un avantage dans des tâches comme celle-ci.

### 3. Prochaines étapes

Pour améliorer davantage les performances du modèle, les prochaines étapes pourraient inclure:

*   **Hyperparamètres du Random Forest:** Optimiser les hyperparamètres du modèle Random Forest (par exemple, `n_estimators`, `max_depth`, `min_samples_leaf`) via des techniques comme la recherche en grille (`GridSearchCV`) ou la recherche aléatoire (`RandomizedSearchCV`).
*   **Autres techniques d'équilibrage:** Explorer d'autres méthodes de gestion du déséquilibre des classes, comme l'undersampling intelligent (ex: `EditedNearestNeighbours`, `NearMiss`) ou des approches hybrides.
*   **Validation plus poussée:** Utiliser des techniques de validation croisée plus sophistiquées ou des ensembles de test indépendants pour garantir la généralisation du modèle.

#Partie 5 - Entraînement et validation



*   Séparer les données en ensembles d’entraînement et de test.
"""

from sklearn.model_selection import train_test_split

# Assuming X_resampled and y_resampled are available from the SMOTE cell
# X_resampled: Features (SBERT embeddings after PCA and SMOTE)
# y_resampled: Labels (after SMOTE)

# Check if X_resampled and y_resampled exist in the current scope
if 'X_resampled' not in locals() or 'y_resampled' not in locals():
    raise NameError("X_resampled or y_resampled not found. Please ensure the SMOTE cell has been run successfully.")

# Separate data into training and testing sets
# test_size=0.2 means 20% of the data will be used for testing
# random_state for reproducibility
# stratify=y_resampled ensures that the proportion of classes is the same in training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\nClass distribution in y_train:\n", y_train.value_counts())
print("\nClass distribution in y_test:\n", y_test.value_counts())

"""

*   Utiliser une validation croisée adaptée

"""

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
import numpy as np

# Ensure X_resampled and y_resampled are available from the SMOTE cell
# If not, the notebook should be re-run from the SMOTE step.
if 'X_resampled' not in locals() or 'y_resampled' not in locals():
    raise NameError("X_resampled or y_resampled not found. Please ensure the SMOTE cell has been run successfully.")

print("Performing stratified K-Fold Cross-Validation with Logistic Regression...")

# Initialize Stratified K-Fold Cross-Validation
# n_splits: number of folds (commonly 5 or 10)
# shuffle: whether to shuffle the data before splitting (important for reproducibility with random_state)
# random_state: for reproducibility
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Initialize the Logistic Regression model (same as used in previous evaluation)
log_reg_model_cv = LogisticRegression(random_state=42, solver='liblinear', max_iter=1000)

# Perform cross-validation
# The scoring parameter can be changed to 'precision', 'recall', 'f1' etc.
scores = cross_val_score(log_reg_model_cv, X_resampled, y_resampled, cv=skf, scoring='accuracy', n_jobs=-1)

print(f"\nCross-validation accuracies: {scores}")
print(f"Mean accuracy: {np.mean(scores):.4f}")
print(f"Standard deviation of accuracy: {np.std(scores):.4f}")

print("Cross-validation complete.")

"""*   Présenter les métriques obtenues.

Métriques de la Validation Croisée

Les métriques de performance obtenues à partir de la validation croisée sont les suivantes:

*   **Scores d'accuracy pour chaque pli (fold):**
    `[0.69408597, 0.69334324, 0.69696407, 0.69334324, 0.68893325]`

*   **Accuracy moyenne:**
    `0.6933`

*   **Écart-type de l'accuracy:**
    `0.0026`

Ces résultats montrent une performance stable du modèle de régression logistique sur les différents sous-ensembles de données, avec une précision moyenne d'environ 69.33% et une faible variation entre les plis.

Métriques minimales :

*   Accuracy
"""

git remote add origin https://github.com/DIANDA1122/D-tection_de_Tweet_Suspect_2026.git
git branch -M main
git push -u origin main